version: "3.8"

services:
  backend:
    # set container name
    container_name: spacecraft-telemetry-backend
    # build from backend directory
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:${POSTGRES_PORT}/${POSTGRES_DB}
    # expose port 8000
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    # set container name
    container_name: spacecraft-telemetry-frontend
    # build from frontend directory
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_WEBSOCKET_URL: ws://localhost:8000/ws/telemetry
    # expose port 80
    ports:
      - "80:80"
    depends_on:
      - backend

  database:
    # set container name
    container_name: spacecraft-telemetry-database
    # build from docker repository image
    image: postgres:18.4
    # perform healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    # set environment variables with values from .env file
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: ${POSTGRES_DB}
    # mount database data to container
    volumes:
      - postgres-data:/var/lib/postgresql
    # expose port 5432
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

volumes:
  postgres-data:
