name: Manual CI/CD Deployments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - feature
          - dev
          - prod
      branch:
        description: 'Branch to deploy (required for feature deployments)'
        required: false
        default: ''
      teardown:
        description: 'Teardown instead of deploy?'
        required: false
        default: 'false'
        type: boolean

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      branch: ${{ github.event.inputs.branch }}
      teardown: ${{ github.event.inputs.teardown }}

  build_push:
    needs: setup
    uses: ./.github/workflows/build_push.yml
    with:
      IMAGE_TAG: ${{ jobs.setup.outputs.IMAGE_TAG }}

  k8s_deploy:
    if: ${{ jobs.setup.outputs.TEARDOWN == 'false' }}
    needs: build_push
    uses: ./.github/workflows/k8s_deploy.yml
    with:
      K8S_NAMESPACE: ${{ jobs.setup.outputs.K8S_NAMESPACE }}

  dns_frontend:
    if: ${{ jobs.setup.outputs.TEARDOWN == 'false' }}
    needs: k8s_deploy
    uses: ./.github/workflows/dns_frontend.yml
    with:
      DOMAIN: ${{ jobs.setup.outputs.DOMAIN }}
      S3_PREFIX: ${{ jobs.setup.outputs.S3_PREFIX }}
      FRONTEND_BUCKET: ${{ jobs.setup.outputs.FRONTEND_BUCKET }}
      CLOUDFRONT_DIST_ID: ${{ jobs.setup.outputs.CLOUDFRONT_DIST_ID }}
      ALB_HOSTNAME: ${{ jobs.k8s_deploy.outputs.ALB_HOSTNAME }}

  teardown:
    if: ${{ jobs.setup.outputs.TEARDOWN == 'true' }}
    needs: setup
    uses: ./.github/workflows/teardown.yml
    with:
      K8S_NAMESPACE: ${{ jobs.setup.outputs.K8S_NAMESPACE }}
      IMAGE_TAG: ${{ jobs.setup.outputs.IMAGE_TAG }}
      S3_PREFIX: ${{ jobs.setup.outputs.S3_PREFIX }}
      FRONTEND_BUCKET: ${{ jobs.setup.outputs.FRONTEND_BUCKET }}
      DOMAIN: ${{ jobs.setup.outputs.DOMAIN }}
      TF_VARS_FILE: ${{ jobs.setup.outputs.TF_VARS_FILE }}
